version: 2

sources:
  - name: northwind_etl
    description: This is a replica of the Postgres database used by our client
    tables:
      - name: orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: products
        description: Esta tabela contem informação dos produtos
      - name: shippers
        description: Esta tabela contém informação dos entregadores
      - name: employees
        description: Esta tabela contém informação dos colaboradores
      - name: customers
        description: Esta tabela contém informação dos clientes
      - name: suppliers
        description: Esta tabela contém informação dos fornecedores
      - name: order_details
        description: Esta tabela contém informação das ordens